from dataclasses import dataclass


@dataclass
class RapidReact:
    AUTO_TAXI_POINT_VALUE = 2

    AUTO_UPPER_HUB_POINT_VALUE = 4
    AUTO_LOWER_HUB_POINT_VALUE = 2

    TELEOP_UPPER_HUB_POINT_VALUE = 2
    TELEOP_LOWER_HUB_POINT_VALUE = 1


@dataclass
class ChargedUp:
    AUTO_MOBILITY_POINT_VALUE = 2

    AUTO_HYBRID_NODE_VALUE = 3
    AUTO_MID_NODE_VALUE = 4
    AUTO_TOP_NODE_VALUE = 6

    TELEOP_HYBRID_NODE_VALUE = 2
    TELEOP_MID_NODE_VALUE = 3
    TELEOP_TOP_NODE_VALUE = 5
