# core setup features
year: 2022
event_code: "iri"
run_with_tba: True

# required translation
match_key: "match_key"
team_number: "team_number"

# optional parameters - if it is needed for a data check and is
# not listed, the check will not run

# Charged Up 2023: hyper-specific parameters
auto_cones: "auto_cones"
auto_cubes: "auto_cubes"
auto_docked: "auto_docked"
preloaded: "preloaded"
auto_engaged: "auto_engaged"
teleop_cubes: "teleop_cubes"
teleop_cones: "teleop_cones"
teleop_misses: "teleop_misses"
mobile: "mobile"
docked: "docked"
engaged: "engaged"

# general game parameters
alliance: "alliance"
driver_station: "driver_station"
defense_pct: "defense_pct"
counter_defense_pct: "counter_defense_pct"
defense_rating: "defense_rating"
counter_defense_rating: "counter_defense_rating"
